name: pytest CI

on:
  pull_request:
    branches: [main]

jobs:
  CI:
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: 3.9
      TESTING_DIR: app/test/
    steps:
      - name: Checkout The Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "${{ env.PYTHON_VERSION }}"
      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Configure Poetry and Install Dependencies
        if: steps.changes.outputs.api == 'true'
        run: |
          poetry config --local
          poetry install --no-interaction --no-root
        working-directory: .

      - name: Test
        working-directory: ./${{ env.TESTING_DIR }}
        run: |
          pytest
      - name: Create Cov File
        run: |
          pytest --cov=app ./${{ env.TESTING_DIR }} --cache-clear  > coverage.txt
      - name: Comment Coverage File in PR
        uses: coroo/pytest-coverage-commentator@v1.0.2
